
import java.awt.event.KeyEvent;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Andrew
 */
public class ConnectionDialog extends javax.swing.JDialog {

	/**
	 * Creates new form ConnectionDialog
	 */
	public ConnectionDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		//setLocationRelativeTo(null);
		initComponents();
	}

	public JTextField getPlayerName() {
		return playerName;
	}

	public JTextField getServerAddress() {
		return serverAddress;
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		serverAddress = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		playerName = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Cool Hackathon Game Client");
		setAlwaysOnTop(true);
		setLocationByPlatform(true);
		setMinimumSize(new java.awt.Dimension(300, 150));
		setPreferredSize(new java.awt.Dimension(300, 150));
		getContentPane().setLayout(new java.awt.GridBagLayout());

		serverAddress.setText("localhost");
		serverAddress.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				serverAddressKeyPressed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(serverAddress, gridBagConstraints);

		jButton1.setText("Join");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 2;
		getContentPane().add(jButton1, gridBagConstraints);

		jLabel1.setText("Server address:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(jLabel1, gridBagConstraints);

		jLabel2.setText("Player name:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(jLabel2, gridBagConstraints);

		playerName.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				playerNameKeyPressed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(playerName, gridBagConstraints);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		if (!playerName.getText().trim().isEmpty())
			setVisible(false);
	}//GEN-LAST:event_jButton1ActionPerformed

	private void serverAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serverAddressKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			jButton1.doClick();
		}
	}//GEN-LAST:event_serverAddressKeyPressed

	private void playerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_playerNameKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			jButton1.doClick();
		}
	}//GEN-LAST:event_playerNameKeyPressed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField playerName;
	private javax.swing.JTextField serverAddress;
	// End of variables declaration//GEN-END:variables
}
